[project]
name = "amazon-books"
version = "0.1.0"
description = "Collect groups of customers preferred products when any ASIN is provided."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "pandas>=2.3.0",
    "requests>=2.32.4",
]
